// tests/cses_tests.rs
#[cfg(test)]
mod integration {
    // This pulls in the tests generated by build.rs
    // Because this file is in /tests, Cargo provides the CARGO_BIN_EXE environment variables.
    include!(concat!(env!("OUT_DIR"), "/generated_tests.rs"));
}
